### ISSUE TITLE
erro when try start wallet

### ISSUE THREAD

**Issue by Mokiller** [AugustoResende/RaiLightWallet#6]
```
/home/ubuntu/workspace/main.js:15
const {BrowserWindow} = remote;
                        ^

TypeError: Cannot match against 'undefined' or 'null'.
    at Object.<anonymous> (/home/ubuntu/workspace/main.js:15:25)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:504:3
```

**Comment by augustresende** [comment]
You are using electron?

**Comment by Mokiller** [comment]
@AugustoResende yep

**Comment by augustresende** [comment]
You run npm install? Are trying start using npm start?

**Comment by Mokiller** [comment]
@AugustoResende yeah i try do it but don't work

**Comment by augustresende** [comment]
You need start using npm start...

index.js is default file to start.. not main.js

**Comment by augustresende** [comment]
And.. is not node main, is npm start
